### ISSUE TITLE
Werft ignores the "deleted" trigger

### ISSUE THREAD

**Issue by ArthurSens** [csweichel/werft#114]
**Describe the bug**
Jobs not getting triggered when branches are deleted.

We just introduced a new job that should be triggered whenever a branch is deleted(See https://github.com/gitpod-io/gitpod/pull/8087). However, jobs are not being executed when we delete branches.

**To Reproduce**
Configure a Github repo to trigger jobs on branch deletions

**Expected behavior**
Jobs being executed when branches are deleted

**Comment by ArthurSens** [comment]
It's not only that we're not listening to a Delete event... there is no implementation for processing deletion events. Also, I believe that a deletion event is a form of push, isn't it? There is a special handling [here](https://github.com/csweichel/werft/blob/baf5a1a8f11f23cb4341a4c3e5bcc1545c1c28d5/plugins/github-integration/main.go#L283-L286) that makes me think so.

We'll have to figure out a way to test this to be sure :)

**Comment by csweichel** [comment]
precursor: https://github.com/csweichel/werft/issues/109
