### ISSUE TITLE
The `Owner` field is empty

### ISSUE THREAD

**Issue by wulfthimm** [csweichel/werft#125]
**Describe the bug**

The `Owner` is empty in the dashboard [[1](https://werft.gitpod-dev.com/jobs)].
![image](https://user-images.githubusercontent.com/12035025/156533352-c9818f1f-5e7b-41ec-9ba1-58b8f44463bd.png)

And in the job description [[2](https://werft.gitpod-dev.com/job/gitpod-build-cw-fix-1699.4)].
![image](https://user-images.githubusercontent.com/12035025/156533431-e7c27877-d0d4-4ac1-b87a-5ba8966dbfd2.png)

As the `Owners` of older jobs are still visible I assume the problem is that the `Owner` is no longer extracted from new commits.

**Comment by wulfthimm** [comment]
Maybe it is caused by not parsing the annotations. https://github.com/csweichel/werft/commit/d5e1218fcdecca5c6a09fcb6b00b81f34b5adc03

**Comment by csweichel** [comment]
fixed in https://github.com/csweichel/werft/commit/4a0d3ccc6dffeff5626c48d70a1ae9661fd4fbfc

**Comment by wulfthimm** [comment]
Thanks for solving this problem early.
