### ISSUE TITLE
Website needs a more obvious GitHub repo link

### ISSUE THREAD

**Issue by jankeromnes** [csweichel/werft#53]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't find the GitHub link on a website, even after scrolling up and down multiple times.

Then on a hunch I hovered on the "Learn More" button.

**Describe the solution you'd like**
Maybe adding a small but more explicit GitHub link, or icon, or ribbon somewhere in the page.

**Describe alternatives you've considered**
The "Learn More" button can stay as is, but on its own it doesn't help me to quickly find the GitHub repo.

**Additional context**

**Comment by csweichel** [comment]
Thank you for reporting this.

I have added a GitHub link to the nav bar:
![image](https://user-images.githubusercontent.com/3210701/74102012-d3673280-4b3f-11ea-9c55-0deb88169e2e.png)
