### ISSUE TITLE
"Finished" time is often in the future

### ISSUE THREAD

**Issue by jankeromnes** [csweichel/werft#62]
**Describe the bug**
<img width="150" alt="Screenshot 2020-02-21 at 08 24 14" src="https://user-images.githubusercontent.com/599268/75013075-befe3080-5483-11ea-8058-fcaf7832d0b5.png">

**To Reproduce**
1. Start a build and let it finish
2. Sometimes(?) the "Finished" time is in the future

**Expected behavior**
I think the "Finished" time should be in the past if the build is finished.

Or, if it's a prediction, I think it should be called "Estimated to finish".

**Comment by csweichel** [comment]
The "Finished" field is supposed to express a duration rather than a point in time. It should probably be called _Duration_ instead.

**Comment by jankeromnes** [comment]
Aha, makes sense, thanks! I'll make a PR. 🙂
