### ISSUE TITLE
Simpler way to update the job list in on the "start job" page

### ISSUE THREAD

**Issue by meysholdt** [csweichel/werft#96]
Currently, when you you add/modify/delete jobs in git, those changes are not reflected on the "start job" webUI unless you run `kubectl rollout restart statefulset werft`.

It would be nice if weft would pull in those changes automatically of (if this is problematic due to performance) offer a "refresh" button on the "start job" webUI.

**Comment by csweichel** [comment]
werft already picks up those changes after a while, I believe the default is 30 minutes

**Comment by csweichel** [comment]
Werft now pulls the job spec every 10 minutes. This interval is [configurable](https://github.com/csweichel/werft/blob/baf5a1a8f11f23cb4341a4c3e5bcc1545c1c28d5/cmd/server/run.go#L480) like
```
service:
    specUpdateInterval: 10m
```
